name: marketplace

services:
  app:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: marketplace_backend
    ports:
      - "${PORT:-3333}:3333"
    depends_on:
      - db
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-marketplace}?schema=public
      - NODE_ENV=development
    restart: unless-stopped

  db:
    image: postgres:14-alpine
    container_name: marketplace_db
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-marketplace}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  prisma-studio:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: prisma_studio
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-marketplace}?schema=public
    ports:
      - "${PRISMA_STUDIO_PORT:-5555}:5555"
    entrypoint: []
    command: npx prisma studio --schema src/infra/database/prisma/schema.prisma
    restart: unless-stopped

volumes:
  postgres_data: