services:
  app:
    build: .
    container_name: marketplace_api
    ports:
      - "3333:3333"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/marketplace?schema=public
      - NODE_ENV=development
    volumes:
      - ./:/app
      - /app/node_modules
    command: sh -c "npx prisma migrate deploy && yarn dev"
    restart: unless-stopped

  db:
    image: postgres:14-alpine
    container_name: marketplace_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=marketplace
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  prisma-studio:
    build: .
    container_name: prisma_studio
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/marketplace?schema=public
    ports:
      - "5555:5555"
    command: npx prisma studio
    restart: unless-stopped

volumes:
  postgres_data: