services:
  app:
    build: .
    container_name: marketplace_api
    ports:
      - "3333:3333"
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=${NODE_ENV}
    volumes:
      - ./:/app
      - /app/node_modules
    command: sh -c "yarn prisma:migrate && yarn dev"
    restart: unless-stopped

  db:
    image: postgres:14-alpine
    container_name: marketplace_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  prisma-studio:
    build: .
    container_name: prisma_studio
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "5555:5555"
    command: npx prisma studio --schema src/infra/database/prisma/schema.prisma
    restart: unless-stopped

volumes:
  postgres_data: